#!/usr/bin/env python3
"""Extract clean guessing sentences from the cached Gutenberg corpus
(experiments/english-redundancy/corpus/) into sentences.js.

Filters: 40-80 chars after normalizing to a-z+space, 8-16 words, every word
common in the corpus (kills names and archaisms), no single-letter words
except a/i (kills contraction artifacts like "don t"). Deterministic shuffle.
"""

import json
import random
import re
from collections import Counter
from pathlib import Path

CORPUS = Path(__file__).parent / "../../experiments/english-redundancy/corpus"
OUT = Path(__file__).parent / "sentences.js"
N_SENTENCES = 150
MIN_WORD_FREQ = 40


def load() -> str:
    text = ""
    for f in sorted(CORPUS.glob("*.txt")):
        raw = f.read_text(encoding="utf-8", errors="ignore")
        s = re.search(r"\*\*\* ?START OF.*?\*\*\*", raw, re.S)
        e = re.search(r"\*\*\* ?END OF", raw)
        text += raw[s.end() if s else 0 : e.start() if e else len(raw)] + "\n"
    return text


def normalize(s: str) -> str:
    s = re.sub(r"[^a-zA-Z]+", " ", s).lower()
    return re.sub(r" +", " ", s).strip()


def main() -> None:
    text = load()
    freq = Counter(normalize(text).split())

    candidates = []
    for raw in re.split(r"[.!?;]+", text.replace("\r\n", " ").replace("\n", " ")):
        s = normalize(raw)
        if not (40 <= len(s) <= 80):
            continue
        words = s.split()
        if not (8 <= len(words) <= 16):
            continue
        if any(len(w) == 1 and w not in ("a", "i") for w in words):
            continue
        if any(freq[w] < MIN_WORD_FREQ for w in words):
            continue
        candidates.append(s)

    candidates = sorted(set(candidates))
    random.Random(1948).shuffle(candidates)
    chosen = candidates[:N_SENTENCES]
    OUT.write_text(
        "// generated by make_sentences.py — do not edit by hand\n"
        "const SENTENCES = " + json.dumps(chosen, indent=2) + ";\n"
    )
    print(f"{len(candidates)} candidates -> wrote {len(chosen)} sentences")
    for s in chosen[:6]:
        print("  ", s)


if __name__ == "__main__":
    main()
