#!/usr/bin/env python3
"""Build the transmitter's codebooks from the cached Gutenberg corpus
(experiments/english-redundancy/corpus/) into codebook.js.

Alphabet: 32 symbols = space, a-z, and . , ' ? ! -- exactly 5 bits each for
the plain teleprinter-style code. The "compress" option uses a Huffman code
built from these corpus frequencies (short codewords for common symbols).
The normalization here must match normalize() in game.js.
"""

import heapq
import json
import math
import re
from collections import Counter
from pathlib import Path

CORPUS = Path(__file__).parent / "../../experiments/english-redundancy/corpus"
OUT = Path(__file__).parent / "codebook.js"
ALPHABET = " abcdefghijklmnopqrstuvwxyz.,'?!"


def load() -> str:
    text = ""
    for f in sorted(CORPUS.glob("*.txt")):
        raw = f.read_text(encoding="utf-8", errors="ignore")
        s = re.search(r"\*\*\* ?START OF.*?\*\*\*", raw, re.S)
        e = re.search(r"\*\*\* ?END OF", raw)
        text += raw[s.end() if s else 0 : e.start() if e else len(raw)] + "\n"
    return text


def normalize(s: str) -> str:
    s = s.lower()
    s = re.sub(r"[‘’`]", "'", s)
    s = re.sub(r'["“”]', "", s)
    s = re.sub(r"[;:]", ",", s)
    s = re.sub(r"[^a-z.,'?! ]+", " ", s)
    return re.sub(r" +", " ", s).strip()


def huffman(counts: dict) -> dict:
    """Code lengths by Huffman's algorithm, then canonical codewords
    (sorted by length, then alphabet order) so the table is reproducible."""
    heap = [(n, i, [sym]) for i, (sym, n) in enumerate(counts.items())]
    heapq.heapify(heap)
    depth = Counter()
    tie = len(heap)
    while len(heap) > 1:
        n1, _, s1 = heapq.heappop(heap)
        n2, _, s2 = heapq.heappop(heap)
        for sym in s1 + s2:
            depth[sym] += 1
        heapq.heappush(heap, (n1 + n2, tie, s1 + s2))
        tie += 1
    order = sorted(counts, key=lambda s: (depth[s], ALPHABET.index(s)))
    codes, code, prev_len = {}, 0, depth[order[0]]
    for sym in order:
        code <<= depth[sym] - prev_len
        codes[sym] = format(code, f"0{depth[sym]}b")
        prev_len = depth[sym]
        code += 1
    return codes


def main() -> None:
    text = normalize(load())
    c = Counter(text)
    counts = {sym: c[sym] for sym in ALPHABET}
    total = sum(counts.values())
    codes = huffman(counts)
    h = -sum(n / total * math.log2(n / total) for n in counts.values() if n)
    avg = sum(counts[s] / total * len(codes[s]) for s in ALPHABET)
    per_million = {s: round(counts[s] / total * 1e6) for s in ALPHABET}
    body = (
        "/* Generated by make_codebook.py from the Gutenberg corpus in\n"
        "   experiments/english-redundancy/ -- do not edit by hand.\n"
        f"   {total:,} symbols; single-symbol entropy {h:.3f} bits;\n"
        f"   Huffman average {avg:.3f} bits (plain code: 5). */\n"
        f"const ALPHABET = {json.dumps(ALPHABET)};\n"
        f"const SYMBOL_FREQ = {json.dumps(per_million)};  // per million\n"
        f"const HUFFMAN = {json.dumps(codes)};\n"
        f"const HUFFMAN_AVG = {avg:.3f};\n"
        f"const SYMBOL_ENTROPY = {h:.3f};\n"
    )
    OUT.write_text(body)
    print(f"{total:,} symbols  H1={h:.3f}  huffman avg={avg:.3f}")
    for s in sorted(ALPHABET, key=lambda s: -counts[s]):
        print(repr(s), f"{counts[s]/total:.4f}", codes[s])


if __name__ == "__main__":
    main()
